//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace BloodLife.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT()
        {
            this.REQUESTS = new HashSet<REQUEST>();
        }

        public string PATNUMBER { get; set; }
        public string PATNUMBERSHORT
        {
            get { return PATNUMBER != null ? PATNUMBER.Substring(12, 8) : ""; }
        }
        public Nullable<double> PATCREATIONDATE { get; set; }
        public string HOSPNUMBER { get; set; }
        public string BENNUMBER { get; set; }
        public string INTNUM { get; set; }
        public string NAME { get; set; }
        public string MAIDENNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string PATTITLE { get; set; }
        [DisplayFormat(DataFormatString ="{0: dd MMM yyyy}")]
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<byte> SEX { get; set; }
        public string SEXLONG
        {
            get
            {
                switch (SEX)
                {
                    case 0:
                        { return SEX != null ? "Male" : ""; }
                    case 1:
                        { return SEX != null ? "Female" : ""; }
                    case 2:
                        { return SEX != null ? "Unknown" : ""; }
                    default:
                        { return SEX != null ? "Unknown" : ""; }   
                }
            }
        }

        public string PATGROUP { get; set; }
        public string ANTIBODIES { get; set; }
        public string ABSHORT
        {
            get { return ANTIBODIES != null ? ANTIBODIES.Substring(0, 5) : ""; }
        }
        public string REQUIREMENTS { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string TELEPHON { get; set; }
        public string REFDOCTOR { get; set; }
        public string REFLOCATION { get; set; }
        public Nullable<byte> RECBYCNX { get; set; }
        public string LINKNUMBER { get; set; }
        public Nullable<byte> LINKTYPE { get; set; }
        public string ABO { get; set; }
        public string RHFACTOR { get; set; }
        public string RHPHENO { get; set; }
        public string KELL { get; set; }
        public Nullable<byte> BGRPSTATUS { get; set; }
        public Nullable<System.DateTime> BGRPSTATUSDATE { get; set; }
        public string BGRPSTATUSUID { get; set; }
        public string ETHNICORIGIN { get; set; }
        public string RELIGION { get; set; }
        public string MOPATNUMBER { get; set; }
        public Nullable<int> ANID { get; set; }
        public Nullable<byte> MANDATORYXMATCH { get; set; }
        public Nullable<byte> SAFETYMEASURES { get; set; }
        public Nullable<byte> BGRPSTATUSTMP { get; set; }
        public string LOGUSERID { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public string ADDITIONALDATA { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUESTS { get; set; }
    }
}
